<div class="wrap">
	<div class="box_center">
		<!-- ITEM DESCRIPTION -->
		<div class="item-Title"><?php echo $this->itemData["Title"]; ?></div>
		<div class="item-Manufac">Brand Name</div>
		<div id="itemInfoContainer">
			<div id="itemPhotoContainer">
				<div id="displayImage">
					<img src="<?php echo $this->itemData["MediumImageUrl"]; ?>"/>
				</div>
				<div class="thumbnailImages">
					
				</div>
			</div>
			<div id="itemDescContainer">
				<div class="item-ListPrice"><span class="category">List Price: </span><?php echo $this->itemData["ListPrice"]; ?></div>
				<div class="item-CurrPrice"><span class="category">Current Price: </span><?php echo $this->itemData["ListPrice"]; ?></div>
				<div class="item-currentStockContainer">
					<span>Current Stock:<span>
					<ul>
						<li><span class="category">New:</span> <?php echo $this->itemData["StockNew"]; ?></li>
						<li><span class="category">Used:</span> <?php echo $this->itemData["StockUsed"]; ?></li>
					</ul>
				</div>
			</div>
		</div>
		<div id="createAlertContainer">
			<h1>Create Alert</h1>
			<div class="alertSettingsContainer">
				<h2>Price: </h2>
				<label for="anyPriceChange">Any Price Decrease</label><input type="checkbox" id="anyPriceChange"/>
				<div id="priceSlider" style="width:200px"></div>
				<h2>Expires:</h2>
				<p>Date: <input id="expires" type="text"></p>
			</div>
		</div>
		
		
		
	</div>
</div>

<script>
	$(function() {
		$( "#priceSlider" ).slider();
		$( "#expires").datepicker();
	});
</script>
