<div class="wrap">
	<div class="box_center">
		<!-- ITEM DESCRIPTION -->
		<div class="item-Title"><?php echo $this->itemData["Title"]; ?></div>!!!
		<div class="item-Manufac">Brand Name</div>
		<div id="itemInfoContainer">
			<div id="itemPhotoContainer">
				<div id="displayImage">
					<img src="<?php echo $this->itemData["MediumImageUrl"]; ?>"/>
				</div>
				<div class="thumbnailImages">
					
				</div>
			</div>
			<div id="itemDescContainer">
				<div class="item-ListPrice"><span class="category">List Price: </span><?php echo $this->itemData["ListPrice"]; ?></div>
				<div class="item-CurrPrice"><span class="category">Current Price: </span><?php echo $this->itemData["ListPrice"]; ?></div>
				<div class="item-currentStockContainer">
					<span>Current Stock:<span>
					<ul>
						<li><span class="category">New:</span> <?php echo $this->itemData["StockNew"]; ?></li>
						<li><span class="category">Used:</span> <?php echo $this->itemData["StockUsed"]; ?></li>
					</ul>
				</div>
			</div>
		</div>
		<div id="createAlertContainer">
			<h1>Create Alert</h1>
			<div class="alertSettingsContainer">
				<h2>Price: </h2><span id="sliderPrice"></span>
				<label for="anyPriceChange">Any Price Decrease</label><input type="checkbox" id="anyPriceChange"/>
				<div id="priceSlider" style="width:200px"></div>
				<h2>Expires:</h2>
				<p>Date: <input id="expires" type="text"></p>
				<input id="addItem" type="button" value="Watch Item" />
			</div>
		</div>
		
		
		
	</div>
</div>

<script>
	$(function() {
		
		var defaultPrice = <?php echo $this->itemData["ListPrice"]; ?>*.75;
	
		$( "#priceSlider" ).slider({
			value:defaultPrice,
			min: 0,
			max: <?php echo $this->itemData["ListPrice"]; ?>,
			step: 10,
			slide: function( event, ui ) {
				console.log(ui.value);
				console.log("$"+ui.value);
				$("#sliderPrice").html( "$" + ui.value );
			}
		});
		$( "#sliderPrice" ).html( "$" + $( "#priceSlider" ).slider( "value" ) );

		$( "#expires").datepicker();
		
		$("#addItem").click(function(){
			$.ajax({
				url: "/submit/addItem",
				type: "POST",
				data: {
					"userID" : "1",
					"itemID" : "35",
					"currentPrice" : "<?php echo $this->itemData["ListPrice"]; ?>",
					"dealPrice" : $( "#priceSlider" ).slider( "value" ),
					"expiration" : $("#expires").val()
					},
				success: function(msg){
					alert(msg);
				}
		   });
		});
	});
</script>
