<div class="wrap">
	<div class="box_center">
		<!-- ITEM DESCRIPTION -->
		<div id="itemInfoContainer">
			<div id="itemPhotoContainer">
				<div id="displayImage">
					<img src="http://ecx.images-amazon.com/images/I/41gEGRVgNyL._SL500_AA300_.jpg"/>
				</div>
				<div class="thumbnailImages">
					
				</div>
			</div>
			<div id="itemDescContainer">
				<div class="item-Title">OtterBox Defender-Series Shield for the HTC DROID Incredible (Black)</div>
				<div class="item-Manufac">By: OtterBox</div>
				<div class="item-Price">Current Price: $45.00</div>
				<div class="item-currentStockContainer">
					<span>Current Stock:<span>
					<ul>
						<li>New: 10</li>
						<li>Used: 3</li>
						<li>Refirbished: 5</li>
					</ul>
				</div>
			</div>
		</div>
		<div id="createAlertContainer">
			
		</div>
		
		
		
	</div>
</div>