<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html lang="en-US" xml:lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
<link href="/css/main.css" media="screen" rel="stylesheet" type="text/css" />
<div class="wrap">

	
	<div class="box_center">
		<span id="main_tagline">Pick <span class="emphasis">it.</span> Price <span class="emphasis">it. </span>Buy <span class="emphasis">it.</span>  </span>
		<!-- <h1 id="main_tagline">Pick <span class="emphasis">your</span> item. Choose <span class="emphasis">your</span> price. And we’ll tell <span class="emphasis">you</span> when it’s time to buy!  </h1> -->
		
		<div class="landing_signup_city" id="landing_signup">
            <form method="POST" id="bodysignup">
                
                
                
                <div class="formbox">
                    <input type="text" id="amazon-url" class="forminput autoClearInput" value="Amazon Product URL" title="amazon-url" name="amazon-url">
                </div> 
                <div class="formbox formbox_right"> 
                <input id="pickItemBtn" type="button" value="Let's Get Started!" class="formbutton">
                </div> 
                <p class="clear"></p>
                <div class="promise"><small>Enter the URL to your product on amazon!</small></div> 
                <p class="clear"></p>
            </form> 
        </div>
				<br /><br />
                <div class="mockRecentlyPurchased">
					<img src="../img/recentlypurchased.png" />
                </div>
	</div>
</div>

<script type="text/javascript">

$(function() {
	//Logic to clear text field 
	$(".autoClearInput").bind("blur focus",function(e){
		console.log("HEY");	
        var field = e.target;
        if (field.defaultValue === field.value){
            field.value = '';
            $(field).removeClass("fm-empty");
        }
        else if (field.value === ''){
            field.value = field.defaultValue;
            $(field).addClass("fm-empty");
        }
    });
    
    $("#pickItemBtn").click(function(event){
		var link = $("#amazon-url").val();
		console.log("Clicked");
		console.log($(link).val());
		if(link.length < 1 || link === "Amazon Product URL"){
			alert("You have to enter an Amazon URL");
		}else{
			//Pull out ID from amazon URL
			var pattern =  /(\/dp\/)(.*)(\/)/g;
			var amazonID = link.match(pattern)[0].split("/")[2];	
			if(amazonID.length > 0){
				window.location = "/addItem/"+amazonID;
			}
		}
    });
    
    
    
    
});


</script>