<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html lang="en-US" xml:lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
<link href="/css/main.css" media="screen" rel="stylesheet" type="text/css" />
<div class="wrap">

	<div id="header" class="header_small">
		<div id="logo"><a href="/">IdleBuy</a></div>
		
		<div class="login">
            <a class="formbutton buttonSignIn fancyboxForm" href="/ajax/ajax_sign_up/">Sign Up</a>
            <a id="login_box_launch" href="/ajax/login_box/">Login</a>
        </div>
	</div>
	
	<div class="box_center">
		<h1 id="main_tagline">Pick <span class="emphasis">it.</span> Price <span class="emphasis">it. </span>Buy <span class="emphasis">it.</span>  </h1>
		<!-- <h1 id="main_tagline">Pick <span class="emphasis">your</span> item. Choose <span class="emphasis">your</span> price. And we’ll tell <span class="emphasis">you</span> when it’s time to buy!  </h1> -->
		
		<div class="landing_signup_city" id="landing_signup">
            <form method="POST" id="bodysignup">
                
                
                
                <div class="formbox">
                    <input type="text" id="amazon-url" class="forminput" value="Amazon Product Link" title="amazon-url" name="amazon-url">
                </div> 
                <div class="formbox formbox_right"> 
                <input type="submit" value="Let's Get Started!" class="formbutton">
                </div> 
                <p class="clear"></p>
                <div class="promise"><small>Enter the URL to your product on amazon.</small></div> 
                <p class="clear"></p>
            </form> 
        </div>
				<br /><br />
                <div class="mockRecentlyPurchased">
					<img src="../img/recentlypurchased.png" />
                </div>
	</div>
</div>