<title><?php echo $this->escape($this->pageTitle); ?> - Central Ohio Hockey</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="Keywords" content="<?php echo $this->keywords; ?>" />
<meta name="Description" content="<?php echo $this->description; ?>" />
<?php $this->headLink()->appendStylesheet('/css/reset.css'); ?> 
<?php $this->headLink()->appendStylesheet('/css/'.$this->style.'.css'); //Likely main.css ?>
<!--[if IE]>
	<?php $this->headLink()->appendStylesheet('/css/fixIE.css'); ?>
<![endif]-->
<?php echo $this->headLink(); ?>

<?php echo $this->headLink()->appendStylesheet('/js/css/start/jquery-ui-1.8.12.custom.css') ?>
<script type="text/javascript" src="/js/js/jquery-1.5.1.min.js"></script>
<script type="text/javascript" src="/js/js/jquery-ui-1.8.12.custom.min.js"></script>